### PR TITLE
#CCR-955 improved tooltip

### PR DESCRIPTION
**Pull request by virtru-dubich**
### Proposed Changes
_Please use the Jira Key followed by the changes_

- CCR-955
  - improved tooltip for files item

### Checklist

- [ ] I have added or updated unit tests
- [ ] I have added or updated integration tests (if appropriate)
- [ ] I have added or updated documentation / readme (if appropriate)
- [ ] I have verified that my changes have not introduced new lint errors
- [x] I have added a GitHub labels to the PR for either _patch_, `minor`, or **major**

### CODE REVIEW

**Review by ntrevino-virtru — CHANGES_REQUESTED** [review]
What problem is this solving?

**Comment by virtru-dubich** [comment]
> 

point 4 in this comment https://virtru.atlassian.net/browse/CCR-955?focusedCommentId=133556

**Comment by ntrevino-virtru** [comment]
> > What problem is this solving?
> 
> point 4 in this comment https://virtru.atlassian.net/browse/CCR-955?focusedCommentId=133556

We should not add things to this repo that are only for one product. That looks like it should be solved by the application. The application should make sure to give the Tooltip component the correct props.

**Comment by virtru-dubich** [comment]
> > > What problem is this solving?
> > 
> > 
> > point 4 in this comment https://virtru.atlassian.net/browse/CCR-955?focusedCommentId=133556
> 
> We should not add things to this repo that are only for one product. That looks like it should be solved by the application. The application should make sure to give the Tooltip component the correct props.

This issue can be in any product if we will pass not an only string. In the tooltip, we can use any tags

**Comment by ntrevino-virtru** [comment]
> > > > What problem is this solving?
> > > 
> > > 
> > > point 4 in this comment https://virtru.atlassian.net/browse/CCR-955?focusedCommentId=133556
> > 
> > 
> > We should not add things to this repo that are only for one product. That looks like it should be solved by the application. The application should make sure to give the Tooltip component the correct props.
> 
> This issue can be in any product if we will pass not an only string. In the tooltip, we can use any tags

React components should not expect to display HTML. They should expect to display JSX. Using HTML inside of React components is an anti-pattern, and as a reusable library Virtuoso should be very opinionated about this.

**Pull request closed without merging**
