### PR TITLE
feat(tooltip): add error variant, visible on render

### PR DESCRIPTION
**Pull request by avkvirtru**
[Abacus designs](https://virtru.invisionapp.com/console/Abacus-ckbgo1s2l01h2014t2hrsyllc/ckgv8ej5s01q4012sgi16gxii/play?frame-cb=1606768595574) have led to a need for an error tooltip. I'm proposing extending the existing Tooltip component to have:

1. an error variant, borrowing from the text input error state
1. a "render" trigger so tooltips are always visible, not just on hover

### Checklist

- [x] I have added or updated unit tests
- [x] I have added or updated integration tests (if appropriate)
- [x] I have added or updated documentation / readme (if appropriate)
- [x] I have verified that my changes have not introduced new lint errors

### Testing Instructions

1. Test the error Tooltip in storybook. All knobs should work in any combination.
1. Compare with the [default Tooltip](https://virtru.github.io/virtuoso-design-system/?path=/story/tooltip--default) and ensure no new problems have been introduced. New props should have defaults that preserve existing behavior.

### CODE REVIEW

**Comment by avkvirtru** [comment]
@jrschumacher @suchak1 here's my first attempt at evolving an existing component. Please have a look together. When ready, **this should be squash and merged.**

**Review by jrschumacher — APPROVED** [review]

**Comment by virtru-github-public** [comment]
:rocket: PR was released in [`v1.13.0`](https://github.com/virtru/virtuoso-design-system/releases/tag/v1.13.0) :rocket:

**Comment by virtru-github-public** [comment]
:rocket: PR was released in [`v1.13.0`](https://github.com/virtru/virtuoso-design-system/releases/tag/v1.13.0) :rocket:

**Comment by virtru-github-public** [comment]
:rocket: PR was released in [`v1.13.0`](https://github.com/virtru/virtuoso-design-system/releases/tag/v1.13.0) :rocket:

**Comment by virtru-github-public** [comment]
:rocket: PR was released in [`v1.13.0`](https://github.com/virtru/virtuoso-design-system/releases/tag/v1.13.0) :rocket:

**Pull request merged**
