### PR TITLE
INT-389: Dropped `value` and `defaultValue` support and replaced by `editorState`

### PR DESCRIPTION
**Pull request by riabokon-virtru**
### Proposed Changes

- [INT-389](https://virtru.atlassian.net/browse/INT-389)
  - dropped `value` and `defaultValue` support and replaced by `editorState`

### Checklist

- [x] I have added or updated unit tests
- [ ] I have added or updated integration tests (if appropriate)
- [ ] I have added or updated documentation / readme (if appropriate)
- [x] I have verified that my changes have not introduced new lint errors
- [x] I have added a GitHub labels to the PR for either _patch_, `minor`, or **major**

[INT-389]: https://virtru.atlassian.net/browse/INT-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ntrevino-virtru — COMMENTED** [review]
I'm not sure this is the right way to go. A consumer now needs to know how to use `draft-js` and give the proper `editorState`. What is the motivation for this change?
If the editorState that is passed in has external changes will it automatically sync?

**Comment by riabokon-virtru** [comment]
> I'm not sure this is the right way to go. A consumer now needs to know how to use `draft-js` and give the proper `editorState`. What is the motivation for this change? If the editorState that is passed in has external changes will it automatically sync?

I agree with you. It was a forced step. When I tried to implement a controlled mode based on a string value I faced with a problem when a caret jumped to the beginning of the text. It is a known [issue](https://github.com/facebookarchive/draft-js/issues/1198) in DraftJS. Also, because DraftJS is archived we can be sure that this issue will be not fixed.

We already have a small discussion around replacing DraftJS with something new. You can check this discussion starting from [this message](https://virtru.slack.com/archives/CFDBQD9S5/p1681206228006029)

Maybe you have some thoughts on how to implement a controlled mode in a better way?

**Comment by riabokon-virtru** [comment]
As a solution, we can provide util functions to create `EditorState`

**Comment by ntrevino-virtru** [comment]
Gotcha. Replacing definitely seems like the long-term path. I like the idea of a util function for now though, I think that makes the most sense until we can swap.

**Review by ntrevino-virtru — APPROVED** [review]

**Pull request merged**
